### ISSUE TITLE
My reports doesn't show verified icon

### ISSUE THREAD

**Issue by Chew** [Memerator/Website#49]
#46 is back but this time it's really not there i checked cant fool me this time

**Comment by Drshoboat** [comment]
<img width="1065" alt="Screen Shot 2019-05-02 at 8 05 00 AM" src="https://user-images.githubusercontent.com/42727645/57077200-075c2000-6cb1-11e9-9c44-fbc46ec4bd33.png">
I think you're blind my dude... its right here
