### ISSUE TITLE
Select Age Group of Memes

### ISSUE THREAD

**Issue by Yashtooky** [Memerator/Website#83]
**Is your feature request related to a problem? Please describe.**
  Some memes necessitate swearing for humor.

**Describe the solution you'd like**

I would like swearing to be allowed to a relative degree of acceptability.

**How will this improve Memerator?**

It would open the app to more memers and allow for subjectively funnier memes.

**Describe alternatives you've considered**
 A SFW and NSFW tab. The default would be SFW and you would have to turn on NSFW. This would allow the family friendly part of memerator to still stay. Any NSFW memes could just not be allowed in the Top or Top 10.

**Additional context**

Love you guys <3

**Comment by Chew** [comment]
I think this can be implemented into a "select the age group of the meme"
Is this meme?
[x] Family Friendly
[ ] Teens
[ ] Mature

**Comment by Chew** [comment]
Finally, you can do this! We've written up guidelines for each group, getting less strict as the age goes up. Enjoy!
