### ISSUE TITLE
Tap star to rate on meme lists instead of going to meme page to rate

### ISSUE THREAD

**Issue by Drshoboat** [Memerator/Website#84]
On the recent memes page you can rate memes by clicking the star over the meme, but on other pages you have to go to the meme's page to rate.
**To Reproduce**
Go to any other viewport of memes, i.e. Top Memes
Click on the star above the meme
Rating doesn't change
**Expected behavior**
I would like to be able to rate memes from anywhere there are stars present

**Comment by Chew** [comment]
Thought this was already added, huh. Anyway, this is just a suggestion not fully implemented yet

**Comment by Chew** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Tap star to rate on meme lists instead of going to meme page to rate](https://trello.com/c/Acv8rzgK/39-tap-star-to-rate-on-meme-lists-instead-of-going-to-meme-page-to-rate)

**Comment by Chew** [comment]
Proud to announce this is FINALLY available on all pages! Will be released in the next update on the main site :)

**Comment by Chew** [comment]
Woot woot! Officially released! Thanks for the report!
